project:
  name: "Free Manus AI"
  description: "A free alternative to Manus.im with no limitations"

database:
  engine: "postgresql"
  name: "superagi"
  username: "postgres"
  password: "postgres"
  host: "postgres"
  port: "5432"

vectorstore:
  type: "chroma"
  location: "local"
  path: "/app/vectorstore"

models:
  # For completely free setup, configure a local model
  local:
    enabled: true
    model_name: "llama3"
    path: "/app/models"
  
  # Optional API configuration if you have API keys
  openai:
    api_key: ""  # Leave empty if not using

# Web server configuration
web:
  host: "0.0.0.0"
  port: "8000"

# Redis configuration for task queue
redis:
  host: "redis"
  port: "6379"
  password: ""

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Security settings
security:
  secret_key: "your-secret-key-here"
  token_expiry: 86400  # 24 hours in seconds

# Encryption key must be exactly 32 characters
ENCRYPTION_KEY: "12345678901234567890123456789012"

# Agent configuration
agent:
  default_memory: 100
  max_iterations: 25
  timeout: 600  # 10 minutes in seconds
