version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: superagi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for task queue
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Chroma Vector Database
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - ALLOW_RESET=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  # SuperAGI Backend
  superagi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./models:/app/models
      - ./vectorstore:/app/vectorstore
      - ./workspace:/app/workspace
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/superagi
      - REDIS_URL=redis://redis:6379/0
      - CHROMA_URL=http://chroma:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      chroma:
        condition: service_healthy
    command: >
      bash -c "alembic upgrade head &&
               python -m superagi.api.main"

  # SuperAGI Frontend
  frontend:
    build:
      context: ../web_interface
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://superagi:8000
    depends_on:
      - superagi

volumes:
  postgres_data:
  chroma_data:
